### ISSUE TITLE
Virus detected in Windows release

### ISSUE THREAD

**Issue by gingerbeardman** [RiiConnect24/auto-wiiware-patcher#19]
**Short Description:** 
Virus Detected

**Notes:** 
Google Chrome complains after download
MS Security Essentials complains after extraction

**Patcher Version:** 
- Auto WiiWare Patcher v2.1.8-BugFix1
- Auto WiiWare Patcher v2.1.8

**Operating System:** 
Windows 7 (32-bit)

**Comment by gingerbeardman** [comment]
Workaround: virus not present in `Auto WiiWare Patcher v2.1.7`

**Comment by KcrPL** [comment]
I'm not able to do anything about that. Sorry.
Of course it doesn't have a virus in it.

**Comment by gingerbeardman** [comment]
> I'm not able to do anything about that. Sorry.

So that means close the issue? it's OK for issues to remain open until solved.

> Of course it doesn't have a virus in it.

Well, whether or not that's the case it's currently not possible to download it using Chrome.

Maybe worth looking into it?

**Comment by KcrPL** [comment]
There's nothing I can do about it
