### ISSUE TITLE
help

### ISSUE THREAD

**Issue by four-hundred-and-twenty** [RiiConnect24/auto-wiiware-patcher#21]
it will not download the missing files! what is keeping it from downloading?

**Comment by KcrPL** [comment]
After you download the .zip from [here](https://github.com/RiiConnect24/auto-wiiware-patcher/releases), please extract it to your desktop and then run it and let me know if it works.

**Comment by DarkPhoenix10** [comment]
hm yes extract the zip

**Comment by four-hundred-and-twenty** [comment]
still deletes the files and throws the error message

**Comment by KcrPL** [comment]
Can you make a screenshot and attach it here?

**Comment by four-hundred-and-twenty** [comment]
![1550100839771133659258](https://user-images.githubusercontent.com/47546273/52751591-d1a67580-2fa4-11e9-8bf2-c5d4a6a1464c.jpg)

**Comment by four-hundred-and-twenty** [comment]
![1550100976215-1460880058](https://user-images.githubusercontent.com/47546273/52751664-221dd300-2fa5-11e9-9d0b-79b8a4c0b273.jpg)

**Comment by KcrPL** [comment]
Turn off your antivirus and try again.
