### ISSUE TITLE
Failed to patch?

### ISSUE THREAD

**Issue by gatekeeper1122** [RiiConnect24/auto-wiiware-patcher#22]
**Short Description: Drag the wads into the folder with the "patcher.bat" [like so](https://i.imgur.com/p7ciSjY.png) & i launch it then get [results of this error](https://i.imgur.com/T2ULNMv.png) with any other wad game i try the ones im trying todo are the "pokemon mystery dungeons wii" **

**Patcher Version: [Wiimmfi WiiWarePatcher v2.1.8-BugFix1 - WiiWare Patcher v0.2](https://i.imgur.com/pllHUzD.png)**

**Operating System: Windows 10**

**Comment by larsenv** [comment]
Hi,

You have to run the batch script. It doesn't accept dragging and dropping.

Also, the Pokémon Mystery Dungeon games aren't really confirmed to work on Wiimmfi.

Thanks.

**Comment by gatekeeper1122** [comment]
but there not the only games that it gives that error did you not see it when you clicked on the image link with that error? & i have used that " patcher.bat" it opens the "WiiwarePatcher.exe" by it self after typing 1 & enter

**Comment by KcrPL** [comment]
Hi,

The patcher doesn't work with Drag & Drop. Please put the files (`.WAD games`) to the folder where `patchet.bat` is, run `patcher.bat` and follow the instructions provided.

**Comment by DarkPhoenix10** [comment]
"patchet.bat"
u spelt patcher wrong]

**Comment by KcrPL** [comment]
Thx, fixed lol
