### ISSUE TITLE
Please wait...

### ISSUE THREAD

**Issue by UltraSUPRA** [RiiConnect24/auto-wiiware-patcher#23]
Every time I use the patcher, it gets stuck on the "please wait" screen. I've tried on 2.1.8, 2.1.7, and 2.1.8 Bugfix.
I'm on Windows, in case that might be an issue.

**Comment by UltraSUPRA** [comment]
Six hours, no answer. Just last month, people were getting help the day the issue was posted.

**Comment by mikethedude1** [comment]
Are you connected to the internet?

**Comment by UltraSUPRA** [comment]
> Are you connected to the internet?

Yes.

**Comment by mikethedude1** [comment]
> > Are you connected to the internet?
> 
> Yes.

What version of windows are you running?

**Comment by UltraSUPRA** [comment]
> > > Are you connected to the internet?
> > 
> > 
> > Yes.
> 
> What version of windows are you running?

10.

**Comment by mikethedude1** [comment]
> > > > Are you connected to the internet?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > What version of windows are you running?

What Build (Ex. 1803,1703)

**Comment by UltraSUPRA** [comment]
> > > > > Are you connected to the internet?
> > > > 
> > > > 
> > > > Yes.
> > > 
> > > 
> > > What version of windows are you running?
> 
> What Build (Ex. 1803,1703)

17134.

**Comment by mikethedude1** [comment]
That may be the problem. the latest is 1903 (May 19, im using 1803(october 18)) as you're running April 2018

**Comment by mikethedude1** [comment]
> That may be the problem. the latest is 1903 (May 19, im using 1803(october 18 works fine)) as you're running April 2018

**Comment by UltraSUPRA** [comment]
> > That may be the problem. the latest is 1903 (May 19, im using 1803(october 18 works fine)) as you're running April 2018

So I need to update?

**Comment by Artuto** [comment]
>Six hours, no answer. Just last month, people were getting help the day the issue was posted.

Just a remember that RC24 devs work and offer support for RC24 on our free time, we're people too :)

**Comment by mikethedude1** [comment]
Yeah.
Check Windows Update or Download the Update assistant.

**Comment by mikethedude1** [comment]
oh sorry i got my builds mixed up its 1809 for october

**Comment by KcrPL** [comment]
Jeez... we're people too - RiiConnect24 isn't our job.

Windows build has nothing to do with it. `Please wait` screen is a screen where the patcher is checking for updates.  Right click the patcher.bat and click on `Edit`. Find line 35 and change it to;
>set /a WiiWarePatcher_Update_Activate=0

...save and start the patcher again. I'm not gonna get in details but it's something with your PowerShell on your computer.

It's not a bug, more like an issue with something on your computer.
