### ISSUE TITLE
Never Stop Loading

### ISSUE THREAD

**Issue by Parkeriscoo** [RiiConnect24/auto-wiiware-patcher#24]
Hi On The Auto Wii Ware Patch It Will Just Non-Stop Loading. And I Dont Know Why. I Left It For 10 Minutes And Still Wont Load.

(I Cant Think Of Anything Else. Lol)

Patcher Version: This Version

OS: Windows 10

**Comment by KcrPL** [comment]
Can you try to restart your PC and try again?

**Comment by Parkeriscoo** [comment]
I try that like 50 times and it the same thing

**Comment by KcrPL** [comment]
Looks like it's an issue with Powershell on your PC. What Windows version are you using?

**Comment by Parkeriscoo** [comment]
Version 1709

**Comment by KcrPL** [comment]
I'll look for some solutions, but all I can say for now is that this "bug" is really strange. It only happens to few people so it's really hard to fix.

**Comment by KcrPL** [comment]
Closing it because it's not really a bug but I'll try to make an update soon.

**Comment by DarkPhoenix10** [comment]
HAHAHAHA powershell is bad

**Comment by KcrPL** [comment]
It really is xd
