### ISSUE TITLE
Does not detect wad

### ISSUE THREAD

**Issue by wuniversales** [RiiConnect24/auto-wiiware-patcher#27]
I am trying to patch "Wii Speak", and there is no way to detect wad, linux tells me the file does not exist (I have it put in the script folder).

![image](https://user-images.githubusercontent.com/48658161/80094558-c1096c00-8566-11ea-9bab-b4ab7d228592.png)

And windows just doesn't work, it gets stuck.

Any idea what's going on?

Patcher Version: v2.1.10
Operating System: Linux (Manjaro) and Windows

Edited: In windows work

**Comment by urmum-69** [comment]
Hmm, I haven't tested patching that specific wad. You also don't need to pass the script any arguments

**Comment by urmum-69** [comment]
I just tested, and it worked. Which shell are you using?

**Comment by wuniversales** [comment]
I am using "Konsole", in windows it already works, but it seems that in Linux it does not give the option to patch wii Speak, it also does not detect wads for any strange reason.

**Comment by urmum-69** [comment]
Doesn't answer my question, the terminal emulator you're using is irrelevant. 
Please run `echo $0` and tell me the output.

**Comment by wuniversales** [comment]
Sample `/bin/bash`

**Comment by urmum-69** [comment]
Does the `bin` directory exist?

**Comment by wuniversales** [comment]
Yes.

![image](https://user-images.githubusercontent.com/48658161/80096220-8228e580-8569-11ea-962b-55c08530b7b6.png)

**Comment by urmum-69** [comment]
I mean in the directory you ran the script from.

**Comment by urmum-69** [comment]
Try again, but run `bash patcher.sh` with ***no*** arguments

**Comment by wuniversales** [comment]
No, it doesn't exist.
It seems to work this way.
`cd <path>`
`sh patcher.sh`
Now if such a directory exists.
Thanks for the help.
For whatever reason it works well doing it directly like this.
`sh <path> /patcher.sh`
It would be nice to report this in the readme.

**Comment by 2secslater** [comment]
why are you using `sh` as opposed to `bash`?
we specify to use `bash` at the top of the script for a reason

**Comment by urmum-69** [comment]
@wuniversales Is this safe to close? It seems the reason why it didn't patch them is because they weren't ***in the same directory*** as the script. Please test again, to see if this is the case.

**Comment by wuniversales** [comment]
Yes, now all okey, i close that, thanks :)
