### ISSUE TITLE
Patcher.sh not working on Linux Desktop.

### ISSUE THREAD

**Issue by BalooRJ1** [RiiConnect24/auto-wiiware-patcher#34]
*Short Description: Linux patcher won't run, showing error "/usr/bin/env: ‘bash\r’: No such file or directory"
**Notes:
**Patcher Version: v2.20
**Operating System: Pop OS 20.10.

**Comment by Artuto** [comment]
The heck is a Pop OS

**Comment by SketchMaster2001** [comment]
I swear HTV used PopOS as the machine he wrote this on

**Comment by urmum-69** [comment]
try running dos2unix on this file - it might be that the file is using dos line endings for some reason? that doesn't cause problems on the version of bash I'm using though

**Comment by SketchMaster2001** [comment]
wrong patcher ahhhh

**Comment by BalooRJ1** [comment]
> The heck is a Pop OS

It is a version of Ubuntu developed by System76 that is packaged with the computers they sell. So not a junky distro by any means. The last version of AutoWiiWare worked fine on this same install, but the new one fails.

**Comment by BalooRJ1** [comment]
> try running dos2unix on this file - it might be that the file is using dos line endings for some reason? that doesn't cause problems on the version of bash I'm using though

This did the trick...thanks @urmum-69
